language: node_js
node_js:
  - "lts/*"

script:
  - npm run lint
  - npm run test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on: 
    branch: part-1
